server.port: 8761
eureka.instance.hostname: localhost
eureka.instance.leaseRenewalIntervalInSeconds: 1
eureka.instance.leaseExpirationDurationInSeconds: 2
# 不注册自己
eureka.client.registerWithEureka: false
# 不更新注册的服务信息
eureka.client.fetchRegistry: false
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring.application.name: cloud-eureka-server
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
#eureka:
#  server:
    
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2